### ISSUE TITLE
Alt use of AppBarLayout - Possible to mimic play sotre behavior on "scroll up"/"scroll to top"

### ISSUE THREAD

**Issue by Noitidart** [cesardeazevedo/react-native-collapsing-toolbar#14]
I was trying to use `AppBarLayout` like this:

```
          <AppBarLayoutAndroid
            layoutWidthAndroid="matchParent"
            layoutHeightAndroid="wrapContent"
          >
            {/* Elements directily in <AppBarLayoutAndroid> can have an     */}
            {/* additional scrollFlagsAndroid prop. This must be an array   */}
            {/* of strings, specifying the scroll flags of this element.    */}
            {/* see https://goo.gl/RiAyDX for reference.                    */}
            <View scrollFlagsAndroid={['scroll']}>
              <Text style={{ fontSize: 18 }}>Hi, I will be collapsed when scrolling down, and show again when scrolled to top.</Text>
            </View>
            <View scrollFlagsAndroid={['scroll', 'enterAlways']}>
              <Text style={{ fontSize: 18 }}>Hi, I will be collapsed when scrolling down, and show again when scrolling up.</Text>
            </View>
            <View scrollFlagsAndroid={[]}>
              <Text style={{ fontSize: 18 }}>Hi, I will not be collapsed.</Text>
            </View>
          </AppBarLayoutAndroid>
```

From this discontinued repo - https://github.com/zetavg/react-native-android-design-support#coordinatorlayout

I was hoping to mimic the playstore behavior:

HD screen recording: https://gfycat.com/ShockingQuickGalapagosdove

GIF screen recording: 

![](https://thumbs.gfycat.com/ShockingQuickGalapagosdove-size_restricted.gif)

**Comment by cesardeazevedo** [comment]
Hi, you need to enable the following `scrollFlags`:

`SCROLL_FLAG_SCROLL` | `SCROLL_FLAG_ENTER_ALWAYS_COLLAPSED` | `SCROLL_FLAG_ENTER_ALWAYS`

Here's a practical example.

```jsx
<CollapsingToolbarLayout
  title='Collapsing Toolbar'
  scrollFlags={
      AppBarLayout.SCROLL_FLAG_SCROLL
    | AppBarLayout.SCROLL_FLAG_ENTER_ALWAYS_COLLAPSED
    | AppBarLayout.SCROLL_FLAG_ENTER_ALWAYS
    }>
</CollapsingToolbarLayout>
```

Let me know if you got it.

**Comment by Noitidart** [comment]
Thank you @cesardeazevedo! It's not working yet but i think this is on me. Its great to know this is possible! Thanks for your awesome module and share!!

**Comment by Noitidart** [comment]
I'm trying to create all the demos shown here - https://guides.codepath.com/android/Handling-Scrolls-with-CoordinatorLayout#responding-to-scroll-events

Once I figure each one out I'll share with you here so we can add it to readme to show others. :)

**Comment by Noitidart** [comment]
Does this module also work on bottom bar?

Like this:

![](https://cdn-images-1.medium.com/max/1200/1*5XuieX7b6u2SkLDd9KEJyg.gif)

**Comment by cesardeazevedo** [comment]
It should work since everything is back by a CoordinatorLayout, a truly [BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html) should work, but haven't seen any BottomNavigationView bridge for react-native yet, so can't say how.

**Comment by Noitidart** [comment]
@cesardeazevedo I found a native bottom navigation view in react-native here - https://github.com/prscX/react-native-android-bottom-navigation - but I wasn't able to get it to play nicely as we talked about above. Would you be able to experiement if you have some time maybe? :)

**Comment by cesardeazevedo** [comment]
Thanks for sharing it. 

I just saw they move to a JS solution, sadly 😞 

This is one those things that would play nicely inside a native navigation solution, such as [airbnb native-navigation](https://github.com/airbnb/native-navigation), but that's not something easy to do.

But anyway, i still have my doubts about how that could works, but i will give a try, thanks for sharing it.
