### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by liuhengyi** [cesardeazevedo/react-native-collapsing-toolbar#19]
undefined is not an object (evaluating '_reactNative.UIManager.CTLAppBarLayout.Constants')
<unknown>
    ..\node_modules\react-native-collapsing-toolbar\lib\AppBarLayout.js:11:8
loadModuleImplementation
 
"react": "16.3.0-rc.0"
 "react-native": "0.54.3"

**Comment by cesardeazevedo** [comment]
Did you installed the library correctly? or are you trying to run on iOS?

**Comment by liuhengyi** [comment]
Sorry. I forget link.

**Comment by cesardeazevedo** [comment]
Sometimes happens 😅
