### ISSUE TITLE
I have this issue

### ISSUE THREAD

**Issue by AndrewCloud** [cesardeazevedo/react-native-collapsing-toolbar#2]
![image](https://user-images.githubusercontent.com/12369149/27904258-b1965008-626e-11e7-98e0-cc004e366e97.png)

**Comment by AndrewCloud** [comment]
problem solved

**Comment by cesardeazevedo** [comment]
Glad that you solved that.

**Comment by peterchibunna** [comment]
Please I have the issue above. How did you solve it @AndrewCloud ?
